arch: null
artifacts: null
environment: null
image: alpine/old
packages:
- findutils
repositories: null
secrets:
- 60c74018-5d43-4a31-9bec-55c59e80f0b9
shell: null
sources:
- git@git.sr.ht:~ocurero/asyncinotify_zos
tasks:
- sync_to_github: |
    cd openbm
    git git+ssh://git@github.com/ocurero/asyncinotify_zos.git

triggers: null
